// <auto-generated />
using System;
using Castellan.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Castellan.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CastellanDbContext))]
    [Migration("20260814073046_AddFunds")]
    partial class AddFunds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Castellan.Domain.Aggregates.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankKey")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastReconciledAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastReconciledBalance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiquidityTier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Castellan.Domain.Aggregates.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-7000-8000-000000000001"),
                            IsArchived = false,
                            IsSystem = true,
                            Kind = 0,
                            Name = "Nieprzypisane"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-7000-8000-000000000002"),
                            IsArchived = false,
                            IsSystem = true,
                            Kind = 0,
                            Name = "Nierozpoznane"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-7000-8000-000000000003"),
                            IsArchived = false,
                            IsSystem = true,
                            Kind = 0,
                            Name = "Przelew"
                        });
                });

            modelBuilder.Entity("Castellan.Domain.Aggregates.CategoryRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("HitCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoryRules");
                });

            modelBuilder.Entity("Castellan.Domain.Aggregates.Envelope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MonthBudgetId")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlannedAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MonthBudgetId");

                    b.ToTable("Envelopes", (string)null);
                });

            modelBuilder.Entity("Castellan.Domain.Aggregates.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Deadline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartMonth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TargetAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Funds", (string)null);
                });

            modelBuilder.Entity("Castellan.Domain.Aggregates.MonthBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AvailableFunds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PlannedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Month")
                        .IsUnique();

                    b.ToTable("MonthBudgets");
                });

            modelBuilder.Entity("Castellan.Domain.Aggregates.RawNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParseStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageName");

                    b.HasIndex("ParseStatus");

                    b.HasIndex("PostedAt");

                    b.ToTable("RawNotifications");
                });

            modelBuilder.Entity("Castellan.Domain.Aggregates.Reconciliation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Discrepancy")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("GeneratedTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedBalance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PreviousAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("PreviousBalance")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecordedDelta")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ObservedAt");

                    b.ToTable("Reconciliations");
                });

            modelBuilder.Entity("Castellan.Domain.Aggregates.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MerchantKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProposedTransferGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawMerchant")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RawNotificationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TransferGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Castellan.Domain.Aggregates.Envelope", b =>
                {
                    b.HasOne("Castellan.Domain.Aggregates.MonthBudget", null)
                        .WithMany("Envelopes")
                        .HasForeignKey("MonthBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Castellan.Domain.Aggregates.Reconciliation", b =>
                {
                    b.HasOne("Castellan.Domain.Aggregates.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Castellan.Domain.Aggregates.Transaction", b =>
                {
                    b.HasOne("Castellan.Domain.Aggregates.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Castellan.Domain.Aggregates.MonthBudget", b =>
                {
                    b.Navigation("Envelopes");
                });
#pragma warning restore 612, 618
        }
    }
}
